# Generated by Django 5.2.1 on 2025-05-19 09:07

import calendar
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.RemoveField(
    model_name='budget',
    name='month',
),
migrations.AddField(
    model_name='budget',
    name='month',
    field=models.IntegerField(
        choices=[(i, calendar.month_name[i]) for i in range(1, 13)]
    ),
),

        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'month', 'year')},
        ),
    ]
