# Generated by Django 5.2.1 on 2025-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_budget_created_at_budget_year_alter_budget_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
