# Generated by Django 5.2.1 on 2025-05-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_budget_budget_remaining_budget_budget_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_used',
            new_name='budget_spent',
        ),
    ]
